// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: search.proto

package search

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CodeSearch_Search_FullMethodName = "/search.CodeSearch/Search"
	CodeSearch_Index_FullMethodName  = "/search.CodeSearch/Index"
)

// CodeSearchClient is the client API for CodeSearch service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CodeSearchClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SearchResult], error)
	Index(ctx context.Context, in *IndexRequest, opts ...grpc.CallOption) (*IndexResponse, error)
}

type codeSearchClient struct {
	cc grpc.ClientConnInterface
}

func NewCodeSearchClient(cc grpc.ClientConnInterface) CodeSearchClient {
	return &codeSearchClient{cc}
}

func (c *codeSearchClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SearchResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CodeSearch_ServiceDesc.Streams[0], CodeSearch_Search_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SearchRequest, SearchResult]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CodeSearch_SearchClient = grpc.ServerStreamingClient[SearchResult]

func (c *codeSearchClient) Index(ctx context.Context, in *IndexRequest, opts ...grpc.CallOption) (*IndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IndexResponse)
	err := c.cc.Invoke(ctx, CodeSearch_Index_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CodeSearchServer is the server API for CodeSearch service.
// All implementations must embed UnimplementedCodeSearchServer
// for forward compatibility.
type CodeSearchServer interface {
	Search(*SearchRequest, grpc.ServerStreamingServer[SearchResult]) error
	Index(context.Context, *IndexRequest) (*IndexResponse, error)
	mustEmbedUnimplementedCodeSearchServer()
}

// UnimplementedCodeSearchServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCodeSearchServer struct{}

func (UnimplementedCodeSearchServer) Search(*SearchRequest, grpc.ServerStreamingServer[SearchResult]) error {
	return status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedCodeSearchServer) Index(context.Context, *IndexRequest) (*IndexResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Index not implemented")
}
func (UnimplementedCodeSearchServer) mustEmbedUnimplementedCodeSearchServer() {}
func (UnimplementedCodeSearchServer) testEmbeddedByValue()                    {}

// UnsafeCodeSearchServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CodeSearchServer will
// result in compilation errors.
type UnsafeCodeSearchServer interface {
	mustEmbedUnimplementedCodeSearchServer()
}

func RegisterCodeSearchServer(s grpc.ServiceRegistrar, srv CodeSearchServer) {
	// If the following call panics, it indicates UnimplementedCodeSearchServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CodeSearch_ServiceDesc, srv)
}

func _CodeSearch_Search_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CodeSearchServer).Search(m, &grpc.GenericServerStream[SearchRequest, SearchResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CodeSearch_SearchServer = grpc.ServerStreamingServer[SearchResult]

func _CodeSearch_Index_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CodeSearchServer).Index(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CodeSearch_Index_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CodeSearchServer).Index(ctx, req.(*IndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CodeSearch_ServiceDesc is the grpc.ServiceDesc for CodeSearch service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CodeSearch_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "search.CodeSearch",
	HandlerType: (*CodeSearchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Index",
			Handler:    _CodeSearch_Index_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Search",
			Handler:       _CodeSearch_Search_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "search.proto",
}
