// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: search.proto

package search

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MatchType int32

const (
	MatchType_TEXT              MatchType = 0
	MatchType_SYMBOL_DEFINITION MatchType = 1
	MatchType_SYMBOL_REFERENCE  MatchType = 2
)

// Enum value maps for MatchType.
var (
	MatchType_name = map[int32]string{
		0: "TEXT",
		1: "SYMBOL_DEFINITION",
		2: "SYMBOL_REFERENCE",
	}
	MatchType_value = map[string]int32{
		"TEXT":              0,
		"SYMBOL_DEFINITION": 1,
		"SYMBOL_REFERENCE":  2,
	}
)

func (x MatchType) Enum() *MatchType {
	p := new(MatchType)
	*p = x
	return p
}

func (x MatchType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchType) Descriptor() protoreflect.EnumDescriptor {
	return file_search_proto_enumTypes[0].Descriptor()
}

func (MatchType) Type() protoreflect.EnumType {
	return &file_search_proto_enumTypes[0]
}

func (x MatchType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchType.Descriptor instead.
func (MatchType) EnumDescriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{0}
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	MaxResults    int32                  `protobuf:"varint,2,opt,name=max_results,json=maxResults,proto3" json:"max_results,omitempty"`
	IncludePaths  []string               `protobuf:"bytes,3,rep,name=include_paths,json=includePaths,proto3" json:"include_paths,omitempty"` // Glob patterns for paths to include
	ExcludePaths  []string               `protobuf:"bytes,4,rep,name=exclude_paths,json=excludePaths,proto3" json:"exclude_paths,omitempty"` // Glob patterns for paths to exclude
	IsRegex       bool                   `protobuf:"varint,5,opt,name=is_regex,json=isRegex,proto3" json:"is_regex,omitempty"`               // Treat query as regex pattern
	SymbolsOnly   bool                   `protobuf:"varint,6,opt,name=symbols_only,json=symbolsOnly,proto3" json:"symbols_only,omitempty"`   // Search only in discovered symbols (function/class names)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetMaxResults() int32 {
	if x != nil {
		return x.MaxResults
	}
	return 0
}

func (x *SearchRequest) GetIncludePaths() []string {
	if x != nil {
		return x.IncludePaths
	}
	return nil
}

func (x *SearchRequest) GetExcludePaths() []string {
	if x != nil {
		return x.ExcludePaths
	}
	return nil
}

func (x *SearchRequest) GetIsRegex() bool {
	if x != nil {
		return x.IsRegex
	}
	return false
}

func (x *SearchRequest) GetSymbolsOnly() bool {
	if x != nil {
		return x.SymbolsOnly
	}
	return false
}

type SearchResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FilePath         string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Content          string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	LineNumber       int32                  `protobuf:"varint,3,opt,name=line_number,json=lineNumber,proto3" json:"line_number,omitempty"`
	Score            float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`
	MatchType        MatchType              `protobuf:"varint,5,opt,name=match_type,json=matchType,proto3,enum=search.MatchType" json:"match_type,omitempty"`
	MatchStart       int32                  `protobuf:"varint,6,opt,name=match_start,json=matchStart,proto3" json:"match_start,omitempty"`                   // Start position of match in content
	MatchEnd         int32                  `protobuf:"varint,7,opt,name=match_end,json=matchEnd,proto3" json:"match_end,omitempty"`                         // End position of match in content
	ContentTruncated bool                   `protobuf:"varint,8,opt,name=content_truncated,json=contentTruncated,proto3" json:"content_truncated,omitempty"` // Whether content was truncated from original line
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchResult) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *SearchResult) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SearchResult) GetLineNumber() int32 {
	if x != nil {
		return x.LineNumber
	}
	return 0
}

func (x *SearchResult) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SearchResult) GetMatchType() MatchType {
	if x != nil {
		return x.MatchType
	}
	return MatchType_TEXT
}

func (x *SearchResult) GetMatchStart() int32 {
	if x != nil {
		return x.MatchStart
	}
	return 0
}

func (x *SearchResult) GetMatchEnd() int32 {
	if x != nil {
		return x.MatchEnd
	}
	return 0
}

func (x *SearchResult) GetContentTruncated() bool {
	if x != nil {
		return x.ContentTruncated
	}
	return false
}

type IndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paths         []string               `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexRequest) Reset() {
	*x = IndexRequest{}
	mi := &file_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexRequest) ProtoMessage() {}

func (x *IndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexRequest.ProtoReflect.Descriptor instead.
func (*IndexRequest) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{2}
}

func (x *IndexRequest) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

type IndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilesIndexed  int32                  `protobuf:"varint,1,opt,name=files_indexed,json=filesIndexed,proto3" json:"files_indexed,omitempty"`
	TotalSize     int64                  `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexResponse) Reset() {
	*x = IndexResponse{}
	mi := &file_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexResponse) ProtoMessage() {}

func (x *IndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexResponse.ProtoReflect.Descriptor instead.
func (*IndexResponse) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{3}
}

func (x *IndexResponse) GetFilesIndexed() int32 {
	if x != nil {
		return x.FilesIndexed
	}
	return 0
}

func (x *IndexResponse) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *IndexResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_search_proto protoreflect.FileDescriptor

const file_search_proto_rawDesc = "" +
	"\n" +
	"\fsearch.proto\x12\x06search\"\xce\x01\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1f\n" +
	"\vmax_results\x18\x02 \x01(\x05R\n" +
	"maxResults\x12#\n" +
	"\rinclude_paths\x18\x03 \x03(\tR\fincludePaths\x12#\n" +
	"\rexclude_paths\x18\x04 \x03(\tR\fexcludePaths\x12\x19\n" +
	"\bis_regex\x18\x05 \x01(\bR\aisRegex\x12!\n" +
	"\fsymbols_only\x18\x06 \x01(\bR\vsymbolsOnly\"\x99\x02\n" +
	"\fSearchResult\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1f\n" +
	"\vline_number\x18\x03 \x01(\x05R\n" +
	"lineNumber\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\x120\n" +
	"\n" +
	"match_type\x18\x05 \x01(\x0e2\x11.search.MatchTypeR\tmatchType\x12\x1f\n" +
	"\vmatch_start\x18\x06 \x01(\x05R\n" +
	"matchStart\x12\x1b\n" +
	"\tmatch_end\x18\a \x01(\x05R\bmatchEnd\x12+\n" +
	"\x11content_truncated\x18\b \x01(\bR\x10contentTruncated\"$\n" +
	"\fIndexRequest\x12\x14\n" +
	"\x05paths\x18\x01 \x03(\tR\x05paths\"m\n" +
	"\rIndexResponse\x12#\n" +
	"\rfiles_indexed\x18\x01 \x01(\x05R\ffilesIndexed\x12\x1d\n" +
	"\n" +
	"total_size\x18\x02 \x01(\x03R\ttotalSize\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage*B\n" +
	"\tMatchType\x12\b\n" +
	"\x04TEXT\x10\x00\x12\x15\n" +
	"\x11SYMBOL_DEFINITION\x10\x01\x12\x14\n" +
	"\x10SYMBOL_REFERENCE\x10\x022{\n" +
	"\n" +
	"CodeSearch\x127\n" +
	"\x06Search\x12\x15.search.SearchRequest\x1a\x14.search.SearchResult0\x01\x124\n" +
	"\x05Index\x12\x14.search.IndexRequest\x1a\x15.search.IndexResponseb\x06proto3"

var (
	file_search_proto_rawDescOnce sync.Once
	file_search_proto_rawDescData []byte
)

func file_search_proto_rawDescGZIP() []byte {
	file_search_proto_rawDescOnce.Do(func() {
		file_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_search_proto_rawDesc), len(file_search_proto_rawDesc)))
	})
	return file_search_proto_rawDescData
}

var file_search_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_search_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_search_proto_goTypes = []any{
	(MatchType)(0),        // 0: search.MatchType
	(*SearchRequest)(nil), // 1: search.SearchRequest
	(*SearchResult)(nil),  // 2: search.SearchResult
	(*IndexRequest)(nil),  // 3: search.IndexRequest
	(*IndexResponse)(nil), // 4: search.IndexResponse
}
var file_search_proto_depIdxs = []int32{
	0, // 0: search.SearchResult.match_type:type_name -> search.MatchType
	1, // 1: search.CodeSearch.Search:input_type -> search.SearchRequest
	3, // 2: search.CodeSearch.Index:input_type -> search.IndexRequest
	2, // 3: search.CodeSearch.Search:output_type -> search.SearchResult
	4, // 4: search.CodeSearch.Index:output_type -> search.IndexResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_search_proto_init() }
func file_search_proto_init() {
	if File_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_search_proto_rawDesc), len(file_search_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_search_proto_goTypes,
		DependencyIndexes: file_search_proto_depIdxs,
		EnumInfos:         file_search_proto_enumTypes,
		MessageInfos:      file_search_proto_msgTypes,
	}.Build()
	File_search_proto = out.File
	file_search_proto_goTypes = nil
	file_search_proto_depIdxs = nil
}
