#!/usr/bin/env bash
# Regenerate the reference pages that come from the binaries, so the book
# cannot drift from the code. CI runs this and fails on a diff.
#
#   scripts/docs/generate-reference.sh   (needs a release or debug build; builds one if missing)
set -euo pipefail
cd "$(dirname "$0")/../.."
OUT=docs/book/src/reference

bin() {
  for d in target/release target/debug; do
    [ -x "$d/$1" ] && { echo "$d/$1"; return; }
  done
  cargo build --release --bin "$1" >/dev/null 2>&1
  echo "target/release/$1"
}
FCS=$(bin fcs)
SERVER=$(bin fast_code_search_server)

{
  echo "# \`fcs\` command line"
  echo
  echo "<!-- Generated by scripts/docs/generate-reference.sh from \`fcs --help\`; do not edit. -->"
  echo
  echo "Full help for the client and each subcommand, as printed by the binary."
  echo "The narrative guide is [Command-line client](../imported/cli.md)."
  echo
  for cmd in "" search refs symbols status; do
    if [ -z "$cmd" ]; then echo "## \`fcs --help\`"; else echo "## \`fcs $cmd --help\`"; fi
    echo
    echo '```text'
    NO_COLOR=1 "$FCS" $cmd --help
    echo '```'
    echo
  done
} > "$OUT/cli-help.md"

{
  echo "# Configuration template"
  echo
  echo "<!-- Generated by scripts/docs/generate-reference.sh from \`fast_code_search_server --init\`; do not edit. -->"
  echo
  echo "What \`fast_code_search_server --init config.toml\` writes: every key with its default"
  echo "and the comment that explains it. The narrative reference is [API and configuration](../imported/api.md#configuration-file)."
  echo
  echo '```toml'
  tmp=$(mktemp -d); "$SERVER" --init "$tmp/config.toml" >/dev/null; cat "$tmp/config.toml"; rm -rf "$tmp"
  echo '```'
} > "$OUT/config-template.md"

{
  echo "# Server command line"
  echo
  echo "<!-- Generated by scripts/docs/generate-reference.sh from \`fast_code_search_server --help\`; do not edit. -->"
  echo
  echo '```text'
  "$SERVER" --help
  echo '```'
} > "$OUT/server-help.md"

echo "generated: $OUT/cli-help.md $OUT/config-template.md $OUT/server-help.md"
