// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: semantic_search.proto

package semantic_search

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SemanticCodeSearch_Search_FullMethodName      = "/semantic_search.SemanticCodeSearch/Search"
	SemanticCodeSearch_GetStats_FullMethodName    = "/semantic_search.SemanticCodeSearch/GetStats"
	SemanticCodeSearch_ReloadIndex_FullMethodName = "/semantic_search.SemanticCodeSearch/ReloadIndex"
)

// SemanticCodeSearchClient is the client API for SemanticCodeSearch service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SemanticCodeSearchClient interface {
	// Search for code using natural language query
	Search(ctx context.Context, in *SemanticSearchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SemanticSearchResult], error)
	// Get search engine statistics
	GetStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
	// Reload index from disk
	ReloadIndex(ctx context.Context, in *ReloadIndexRequest, opts ...grpc.CallOption) (*ReloadIndexResponse, error)
}

type semanticCodeSearchClient struct {
	cc grpc.ClientConnInterface
}

func NewSemanticCodeSearchClient(cc grpc.ClientConnInterface) SemanticCodeSearchClient {
	return &semanticCodeSearchClient{cc}
}

func (c *semanticCodeSearchClient) Search(ctx context.Context, in *SemanticSearchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SemanticSearchResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SemanticCodeSearch_ServiceDesc.Streams[0], SemanticCodeSearch_Search_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SemanticSearchRequest, SemanticSearchResult]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SemanticCodeSearch_SearchClient = grpc.ServerStreamingClient[SemanticSearchResult]

func (c *semanticCodeSearchClient) GetStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, SemanticCodeSearch_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *semanticCodeSearchClient) ReloadIndex(ctx context.Context, in *ReloadIndexRequest, opts ...grpc.CallOption) (*ReloadIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReloadIndexResponse)
	err := c.cc.Invoke(ctx, SemanticCodeSearch_ReloadIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SemanticCodeSearchServer is the server API for SemanticCodeSearch service.
// All implementations must embed UnimplementedSemanticCodeSearchServer
// for forward compatibility.
type SemanticCodeSearchServer interface {
	// Search for code using natural language query
	Search(*SemanticSearchRequest, grpc.ServerStreamingServer[SemanticSearchResult]) error
	// Get search engine statistics
	GetStats(context.Context, *StatsRequest) (*StatsResponse, error)
	// Reload index from disk
	ReloadIndex(context.Context, *ReloadIndexRequest) (*ReloadIndexResponse, error)
	mustEmbedUnimplementedSemanticCodeSearchServer()
}

// UnimplementedSemanticCodeSearchServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSemanticCodeSearchServer struct{}

func (UnimplementedSemanticCodeSearchServer) Search(*SemanticSearchRequest, grpc.ServerStreamingServer[SemanticSearchResult]) error {
	return status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedSemanticCodeSearchServer) GetStats(context.Context, *StatsRequest) (*StatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedSemanticCodeSearchServer) ReloadIndex(context.Context, *ReloadIndexRequest) (*ReloadIndexResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReloadIndex not implemented")
}
func (UnimplementedSemanticCodeSearchServer) mustEmbedUnimplementedSemanticCodeSearchServer() {}
func (UnimplementedSemanticCodeSearchServer) testEmbeddedByValue()                            {}

// UnsafeSemanticCodeSearchServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SemanticCodeSearchServer will
// result in compilation errors.
type UnsafeSemanticCodeSearchServer interface {
	mustEmbedUnimplementedSemanticCodeSearchServer()
}

func RegisterSemanticCodeSearchServer(s grpc.ServiceRegistrar, srv SemanticCodeSearchServer) {
	// If the following call panics, it indicates UnimplementedSemanticCodeSearchServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SemanticCodeSearch_ServiceDesc, srv)
}

func _SemanticCodeSearch_Search_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SemanticSearchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SemanticCodeSearchServer).Search(m, &grpc.GenericServerStream[SemanticSearchRequest, SemanticSearchResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SemanticCodeSearch_SearchServer = grpc.ServerStreamingServer[SemanticSearchResult]

func _SemanticCodeSearch_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticCodeSearchServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticCodeSearch_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticCodeSearchServer).GetStats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SemanticCodeSearch_ReloadIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticCodeSearchServer).ReloadIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticCodeSearch_ReloadIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticCodeSearchServer).ReloadIndex(ctx, req.(*ReloadIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SemanticCodeSearch_ServiceDesc is the grpc.ServiceDesc for SemanticCodeSearch service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SemanticCodeSearch_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "semantic_search.SemanticCodeSearch",
	HandlerType: (*SemanticCodeSearchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStats",
			Handler:    _SemanticCodeSearch_GetStats_Handler,
		},
		{
			MethodName: "ReloadIndex",
			Handler:    _SemanticCodeSearch_ReloadIndex_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Search",
			Handler:       _SemanticCodeSearch_Search_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "semantic_search.proto",
}
