// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: semantic_search.proto

package semantic_search

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChunkType int32

const (
	ChunkType_FIXED    ChunkType = 0 // Fixed-size chunk
	ChunkType_FUNCTION ChunkType = 1 // Function chunk
	ChunkType_CLASS    ChunkType = 2 // Class chunk
	ChunkType_MODULE   ChunkType = 3 // Module-level chunk
)

// Enum value maps for ChunkType.
var (
	ChunkType_name = map[int32]string{
		0: "FIXED",
		1: "FUNCTION",
		2: "CLASS",
		3: "MODULE",
	}
	ChunkType_value = map[string]int32{
		"FIXED":    0,
		"FUNCTION": 1,
		"CLASS":    2,
		"MODULE":   3,
	}
)

func (x ChunkType) Enum() *ChunkType {
	p := new(ChunkType)
	*p = x
	return p
}

func (x ChunkType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChunkType) Descriptor() protoreflect.EnumDescriptor {
	return file_semantic_search_proto_enumTypes[0].Descriptor()
}

func (ChunkType) Type() protoreflect.EnumType {
	return &file_semantic_search_proto_enumTypes[0]
}

func (x ChunkType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChunkType.Descriptor instead.
func (ChunkType) EnumDescriptor() ([]byte, []int) {
	return file_semantic_search_proto_rawDescGZIP(), []int{0}
}

type SemanticSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`                              // Natural language query
	MaxResults    int32                  `protobuf:"varint,2,opt,name=max_results,json=maxResults,proto3" json:"max_results,omitempty"` // Maximum number of results to return
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemanticSearchRequest) Reset() {
	*x = SemanticSearchRequest{}
	mi := &file_semantic_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemanticSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemanticSearchRequest) ProtoMessage() {}

func (x *SemanticSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemanticSearchRequest.ProtoReflect.Descriptor instead.
func (*SemanticSearchRequest) Descriptor() ([]byte, []int) {
	return file_semantic_search_proto_rawDescGZIP(), []int{0}
}

func (x *SemanticSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SemanticSearchRequest) GetMaxResults() int32 {
	if x != nil {
		return x.MaxResults
	}
	return 0
}

type SemanticSearchResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FilePath        string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`                                    // Path to the file containing the chunk
	Content         string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                                                      // The code chunk content
	StartLine       int32                  `protobuf:"varint,3,opt,name=start_line,json=startLine,proto3" json:"start_line,omitempty"`                                // Starting line number of chunk
	EndLine         int32                  `protobuf:"varint,4,opt,name=end_line,json=endLine,proto3" json:"end_line,omitempty"`                                      // Ending line number of chunk
	SimilarityScore float32                `protobuf:"fixed32,5,opt,name=similarity_score,json=similarityScore,proto3" json:"similarity_score,omitempty"`             // Similarity score (0-1, higher is better)
	ChunkType       ChunkType              `protobuf:"varint,6,opt,name=chunk_type,json=chunkType,proto3,enum=semantic_search.ChunkType" json:"chunk_type,omitempty"` // Type of code chunk
	SymbolName      string                 `protobuf:"bytes,7,opt,name=symbol_name,json=symbolName,proto3" json:"symbol_name,omitempty"`                              // Symbol name if chunk is a function/class
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SemanticSearchResult) Reset() {
	*x = SemanticSearchResult{}
	mi := &file_semantic_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemanticSearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemanticSearchResult) ProtoMessage() {}

func (x *SemanticSearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemanticSearchResult.ProtoReflect.Descriptor instead.
func (*SemanticSearchResult) Descriptor() ([]byte, []int) {
	return file_semantic_search_proto_rawDescGZIP(), []int{1}
}

func (x *SemanticSearchResult) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *SemanticSearchResult) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SemanticSearchResult) GetStartLine() int32 {
	if x != nil {
		return x.StartLine
	}
	return 0
}

func (x *SemanticSearchResult) GetEndLine() int32 {
	if x != nil {
		return x.EndLine
	}
	return 0
}

func (x *SemanticSearchResult) GetSimilarityScore() float32 {
	if x != nil {
		return x.SimilarityScore
	}
	return 0
}

func (x *SemanticSearchResult) GetChunkType() ChunkType {
	if x != nil {
		return x.ChunkType
	}
	return ChunkType_FIXED
}

func (x *SemanticSearchResult) GetSymbolName() string {
	if x != nil {
		return x.SymbolName
	}
	return ""
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_semantic_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_semantic_search_proto_rawDescGZIP(), []int{2}
}

type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumFiles      int32                  `protobuf:"varint,1,opt,name=num_files,json=numFiles,proto3" json:"num_files,omitempty"`             // Number of indexed files
	NumChunks     int32                  `protobuf:"varint,2,opt,name=num_chunks,json=numChunks,proto3" json:"num_chunks,omitempty"`          // Number of code chunks
	EmbeddingDim  int32                  `protobuf:"varint,3,opt,name=embedding_dim,json=embeddingDim,proto3" json:"embedding_dim,omitempty"` // Embedding dimension
	CacheSize     int32                  `protobuf:"varint,4,opt,name=cache_size,json=cacheSize,proto3" json:"cache_size,omitempty"`          // Query cache size
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_semantic_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_semantic_search_proto_rawDescGZIP(), []int{3}
}

func (x *StatsResponse) GetNumFiles() int32 {
	if x != nil {
		return x.NumFiles
	}
	return 0
}

func (x *StatsResponse) GetNumChunks() int32 {
	if x != nil {
		return x.NumChunks
	}
	return 0
}

func (x *StatsResponse) GetEmbeddingDim() int32 {
	if x != nil {
		return x.EmbeddingDim
	}
	return 0
}

func (x *StatsResponse) GetCacheSize() int32 {
	if x != nil {
		return x.CacheSize
	}
	return 0
}

type ReloadIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexPath     string                 `protobuf:"bytes,1,opt,name=index_path,json=indexPath,proto3" json:"index_path,omitempty"` // Path to index file to load
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadIndexRequest) Reset() {
	*x = ReloadIndexRequest{}
	mi := &file_semantic_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadIndexRequest) ProtoMessage() {}

func (x *ReloadIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadIndexRequest.ProtoReflect.Descriptor instead.
func (*ReloadIndexRequest) Descriptor() ([]byte, []int) {
	return file_semantic_search_proto_rawDescGZIP(), []int{4}
}

func (x *ReloadIndexRequest) GetIndexPath() string {
	if x != nil {
		return x.IndexPath
	}
	return ""
}

type ReloadIndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                      // Whether reload was successful
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                       // Status message
	NumChunks     int32                  `protobuf:"varint,3,opt,name=num_chunks,json=numChunks,proto3" json:"num_chunks,omitempty"` // Number of chunks loaded
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadIndexResponse) Reset() {
	*x = ReloadIndexResponse{}
	mi := &file_semantic_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadIndexResponse) ProtoMessage() {}

func (x *ReloadIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_semantic_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadIndexResponse.ProtoReflect.Descriptor instead.
func (*ReloadIndexResponse) Descriptor() ([]byte, []int) {
	return file_semantic_search_proto_rawDescGZIP(), []int{5}
}

func (x *ReloadIndexResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReloadIndexResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReloadIndexResponse) GetNumChunks() int32 {
	if x != nil {
		return x.NumChunks
	}
	return 0
}

var File_semantic_search_proto protoreflect.FileDescriptor

const file_semantic_search_proto_rawDesc = "" +
	"\n" +
	"\x15semantic_search.proto\x12\x0fsemantic_search\"N\n" +
	"\x15SemanticSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1f\n" +
	"\vmax_results\x18\x02 \x01(\x05R\n" +
	"maxResults\"\x8e\x02\n" +
	"\x14SemanticSearchResult\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"start_line\x18\x03 \x01(\x05R\tstartLine\x12\x19\n" +
	"\bend_line\x18\x04 \x01(\x05R\aendLine\x12)\n" +
	"\x10similarity_score\x18\x05 \x01(\x02R\x0fsimilarityScore\x129\n" +
	"\n" +
	"chunk_type\x18\x06 \x01(\x0e2\x1a.semantic_search.ChunkTypeR\tchunkType\x12\x1f\n" +
	"\vsymbol_name\x18\a \x01(\tR\n" +
	"symbolName\"\x0e\n" +
	"\fStatsRequest\"\x8f\x01\n" +
	"\rStatsResponse\x12\x1b\n" +
	"\tnum_files\x18\x01 \x01(\x05R\bnumFiles\x12\x1d\n" +
	"\n" +
	"num_chunks\x18\x02 \x01(\x05R\tnumChunks\x12#\n" +
	"\rembedding_dim\x18\x03 \x01(\x05R\fembeddingDim\x12\x1d\n" +
	"\n" +
	"cache_size\x18\x04 \x01(\x05R\tcacheSize\"3\n" +
	"\x12ReloadIndexRequest\x12\x1d\n" +
	"\n" +
	"index_path\x18\x01 \x01(\tR\tindexPath\"h\n" +
	"\x13ReloadIndexResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"num_chunks\x18\x03 \x01(\x05R\tnumChunks*;\n" +
	"\tChunkType\x12\t\n" +
	"\x05FIXED\x10\x00\x12\f\n" +
	"\bFUNCTION\x10\x01\x12\t\n" +
	"\x05CLASS\x10\x02\x12\n" +
	"\n" +
	"\x06MODULE\x10\x032\x94\x02\n" +
	"\x12SemanticCodeSearch\x12Y\n" +
	"\x06Search\x12&.semantic_search.SemanticSearchRequest\x1a%.semantic_search.SemanticSearchResult0\x01\x12I\n" +
	"\bGetStats\x12\x1d.semantic_search.StatsRequest\x1a\x1e.semantic_search.StatsResponse\x12X\n" +
	"\vReloadIndex\x12#.semantic_search.ReloadIndexRequest\x1a$.semantic_search.ReloadIndexResponseb\x06proto3"

var (
	file_semantic_search_proto_rawDescOnce sync.Once
	file_semantic_search_proto_rawDescData []byte
)

func file_semantic_search_proto_rawDescGZIP() []byte {
	file_semantic_search_proto_rawDescOnce.Do(func() {
		file_semantic_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_semantic_search_proto_rawDesc), len(file_semantic_search_proto_rawDesc)))
	})
	return file_semantic_search_proto_rawDescData
}

var file_semantic_search_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_semantic_search_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_semantic_search_proto_goTypes = []any{
	(ChunkType)(0),                // 0: semantic_search.ChunkType
	(*SemanticSearchRequest)(nil), // 1: semantic_search.SemanticSearchRequest
	(*SemanticSearchResult)(nil),  // 2: semantic_search.SemanticSearchResult
	(*StatsRequest)(nil),          // 3: semantic_search.StatsRequest
	(*StatsResponse)(nil),         // 4: semantic_search.StatsResponse
	(*ReloadIndexRequest)(nil),    // 5: semantic_search.ReloadIndexRequest
	(*ReloadIndexResponse)(nil),   // 6: semantic_search.ReloadIndexResponse
}
var file_semantic_search_proto_depIdxs = []int32{
	0, // 0: semantic_search.SemanticSearchResult.chunk_type:type_name -> semantic_search.ChunkType
	1, // 1: semantic_search.SemanticCodeSearch.Search:input_type -> semantic_search.SemanticSearchRequest
	3, // 2: semantic_search.SemanticCodeSearch.GetStats:input_type -> semantic_search.StatsRequest
	5, // 3: semantic_search.SemanticCodeSearch.ReloadIndex:input_type -> semantic_search.ReloadIndexRequest
	2, // 4: semantic_search.SemanticCodeSearch.Search:output_type -> semantic_search.SemanticSearchResult
	4, // 5: semantic_search.SemanticCodeSearch.GetStats:output_type -> semantic_search.StatsResponse
	6, // 6: semantic_search.SemanticCodeSearch.ReloadIndex:output_type -> semantic_search.ReloadIndexResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_semantic_search_proto_init() }
func file_semantic_search_proto_init() {
	if File_semantic_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_semantic_search_proto_rawDesc), len(file_semantic_search_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_semantic_search_proto_goTypes,
		DependencyIndexes: file_semantic_search_proto_depIdxs,
		EnumInfos:         file_semantic_search_proto_enumTypes,
		MessageInfos:      file_semantic_search_proto_msgTypes,
	}.Build()
	File_semantic_search_proto = out.File
	file_semantic_search_proto_goTypes = nil
	file_semantic_search_proto_depIdxs = nil
}
